# Generated by Django 3.2.20 on 2023-11-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degreed', '0031_alter_historicaldegreedenterprisecustomerconfiguration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreedenterprisecustomerconfiguration',
            name='enable_incomplete_progress_transmission',
            field=models.BooleanField(default=False, help_text='When set to True, the configured customer will receive learner data transmissions, for incomplete courses as well'),
        ),
        migrations.AddField(
            model_name='historicaldegreedenterprisecustomerconfiguration',
            name='enable_incomplete_progress_transmission',
            field=models.BooleanField(default=False, help_text='When set to True, the configured customer will receive learner data transmissions, for incomplete courses as well'),
        ),
    ]
