# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 02:07
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomer',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_customers', to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomer',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.Site'),
        ),
    ]
