# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-25 04:16


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0019_auto_20170606_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalenrollmentnotificationemailtemplate',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalenterprisecourseenrollment',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomer',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomerentitlement',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaluserdatasharingconsentaudit',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
