# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 11:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0047_auto_20180517_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomeruser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
