# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-10 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0057_enterprisecustomerreportingconfiguration_enterprise_customer_catalogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomer',
            name='customer_type',
            field=models.CharField(choices=[('enterprise', 'Enterprise'), ('partner', 'Partner'), ('non_prod', 'Non Production')], default='enterprise', help_text='Specifies enterprise customer type according to the Partner.', max_length=25),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomer',
            name='customer_type',
            field=models.CharField(choices=[('enterprise', 'Enterprise'), ('partner', 'Partner'), ('non_prod', 'Non Production')], default='enterprise', help_text='Specifies enterprise customer type according to the Partner.', max_length=25),
        ),
    ]
