# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-27 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0069_auto_20190613_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseCatalogQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='All Content', max_length=255)),
                ('content_filter', jsonfield.fields.JSONField(blank=True, default={}, help_text="Query parameters which will be used to filter the discovery service's search/all endpoint results, specified as a Json object. An empty Json object means that all available content items will be included in the catalog.", null=True)),
            ],
            options={
                'ordering': ['created'],
                'verbose_name': 'Enterprise Catalog Query',
                'verbose_name_plural': 'Enterprise Catalog Queries',
            },
        ),
    ]
