# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-27 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0070_enterprisecatalogquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomercatalog',
            name='enterprise_catalog_query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_catalog_queries', to='enterprise.EnterpriseCatalogQuery'),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomercatalog',
            name='enterprise_catalog_query',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enterprise.EnterpriseCatalogQuery'),
        ),
    ]
