# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-02 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0076_auto_20190918_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomerreportingconfiguration',
            name='include_date',
            field=models.BooleanField(default=True, help_text='Include date in the report file name', verbose_name='Include Date'),
        ),
    ]
