# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-18 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0082_AddManagementEnterpriseEnrollmentSource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisecustomeridentityprovider',
            name='enterprise_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_customer_identity_providers', to='enterprise.EnterpriseCustomer'),
        ),
    ]
