# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-07 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0083_enterprisecustomerreportingconfiguration_include_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomeruser',
            name='linked',
            field=models.BooleanField(default=True),
        ),
    ]
