# Generated by Django 2.2.14 on 2020-07-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0104_auto_20200723_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisecustomercatalog',
            name='sync_enterprise_catalog_query',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalenterprisecustomercatalog',
            name='sync_enterprise_catalog_query',
            field=models.BooleanField(default=False),
        ),
    ]
