# Generated by Django 2.2.13 on 2020-07-31 17:51

from django.db import migrations, models
import enterprise.validators


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0104_sync_query_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprisecustomerbrandingconfiguration',
            old_name='banner_background_color',
            new_name='primary_color',
        ),
        migrations.RenameField(
            model_name='enterprisecustomerbrandingconfiguration',
            old_name='banner_border_color',
            new_name='secondary_color',
        ),
        migrations.AddField(
            model_name='enterprisecustomerbrandingconfiguration',
            name='tertiary_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[enterprise.validators.validate_hex_color]),
        ),
    ]
