# Generated by Django 2.2.17 on 2020-11-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0115_enterpriseanalyticsuser_historicalenterpriseanalyticsuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisecustomeridentityprovider',
            name='enterprise_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_customer_identity_providers', to='enterprise.EnterpriseCustomer'),
        ),
    ]
