# Generated by Django 2.2.18 on 2021-02-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0123_add_enable_community_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomeruser',
            name='is_community_member',
            field=models.BooleanField(default=False),
        ),
    ]
