# Generated by Django 2.2.18 on 2021-03-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0124_auto_20210301_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpendingenrollment',
            name='license_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pendingenrollment',
            name='license_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
