# Generated by Django 2.2.19 on 2021-05-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0130_lms_customer_lp_search_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomer',
            name='reply_to',
            field=models.EmailField(blank=True, help_text='Specifies the email address to be used as from email for enterprise emails.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomer',
            name='reply_to',
            field=models.EmailField(blank=True, help_text='Specifies the email address to be used as from email for enterprise emails.', max_length=254, null=True),
        ),
    ]
