# Generated by Django 2.2.20 on 2021-06-03 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0131_auto_20210517_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentnotificationemailtemplate',
            name='template_type',
            field=models.CharField(choices=[('DEFAULT_ENROLL', 'Default Enrollment Template'), ('ADMIN_ENROLL', 'Admin Enrollment Template')], default='DEFAULT_ENROLL', help_text='Use either DEFAULT_ENROLL or ADMIN_ENROLL', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalenrollmentnotificationemailtemplate',
            name='template_type',
            field=models.CharField(choices=[('DEFAULT_ENROLL', 'Default Enrollment Template'), ('ADMIN_ENROLL', 'Admin Enrollment Template')], default='DEFAULT_ENROLL', help_text='Use either DEFAULT_ENROLL or ADMIN_ENROLL', max_length=255),
        ),
        migrations.AlterField(
            model_name='enrollmentnotificationemailtemplate',
            name='enterprise_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_enrollment_templates', to='enterprise.EnterpriseCustomer'),
        ),
    ]
