# Generated by Django 2.2.24 on 2021-09-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0142_auto_20210907_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='CornerstoneCourseKeys',
            fields=[
                ('internal_course_id', models.CharField(help_text='This is the edX course key that is used as a unique identifier.', max_length=255, primary_key=True, serialize=False)),
                ('external_course_id', models.CharField(help_text='This is the course key that is being sent to our partners.', max_length=255)),
            ],
        ),
    ]
