# Generated by Django 3.2.11 on 2022-01-25 20:23

from django.db import migrations, models
import enterprise.models
import enterprise.validators


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0151_add_is_active_to_invite_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisecustomer',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Email to be displayed as public point of contact for enterprise.', max_length=254),
        ),
        migrations.AlterField(
            model_name='enterprisecustomer',
            name='default_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es-419', 'Español (Latinoamérica)')], default=None, help_text='Specifies the default language for all the learners of this enterprise customer.', max_length=25),
        ),
        migrations.AlterField(
            model_name='enterprisecustomer',
            name='reply_to',
            field=models.EmailField(blank=True, default='', help_text="The email address where learner's reply to enterprise emails will be delivered.", max_length=254),
        ),
        migrations.AlterField(
            model_name='enterprisecustomer',
            name='sender_alias',
            field=models.CharField(blank=True, default='', help_text='Specifies enterprise customized sender alias.', max_length=255),
        ),
        migrations.AlterField(
            model_name='enterprisecustomerbrandingconfiguration',
            name='logo',
            field=models.ImageField(blank=True, default='', help_text='Logo images must be in .png format.', max_length=255, upload_to=enterprise.models.logo_path, validators=[enterprise.validators.validate_image_extension, enterprise.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='enterprisecustomerbrandingconfiguration',
            name='primary_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[enterprise.validators.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='enterprisecustomerbrandingconfiguration',
            name='secondary_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[enterprise.validators.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='enterprisecustomerbrandingconfiguration',
            name='tertiary_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[enterprise.validators.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='enterprisecustomerreportingconfiguration',
            name='pgp_encryption_key',
            field=models.TextField(blank=True, default='', help_text='The key for encryption, if PGP encrypted file is required.', verbose_name='PGP Encryption Key'),
        ),
        migrations.AlterField(
            model_name='enterprisecustomerreportingconfiguration',
            name='sftp_file_path',
            field=models.CharField(blank=True, default='', help_text='If the delivery method is sftp, the path on the host to deliver the report to.', max_length=256, verbose_name='SFTP file path'),
        ),
        migrations.AlterField(
            model_name='enterprisecustomerreportingconfiguration',
            name='sftp_hostname',
            field=models.CharField(blank=True, default='', help_text='If the delivery method is sftp, the host to deliver the report to.', max_length=256, verbose_name='SFTP Host name'),
        ),
        migrations.AlterField(
            model_name='enterprisecustomerreportingconfiguration',
            name='sftp_username',
            field=models.CharField(blank=True, default='', help_text='If the delivery method is sftp, the username to use to securely access the host.', max_length=256, verbose_name='SFTP username'),
        ),
        migrations.AlterField(
            model_name='historicalenterprisecustomer',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Email to be displayed as public point of contact for enterprise.', max_length=254),
        ),
        migrations.AlterField(
            model_name='historicalenterprisecustomer',
            name='default_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es-419', 'Español (Latinoamérica)')], default=None, help_text='Specifies the default language for all the learners of this enterprise customer.', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalenterprisecustomer',
            name='reply_to',
            field=models.EmailField(blank=True, default='', help_text="The email address where learner's reply to enterprise emails will be delivered.", max_length=254),
        ),
        migrations.AlterField(
            model_name='historicalenterprisecustomer',
            name='sender_alias',
            field=models.CharField(blank=True, default='', help_text='Specifies enterprise customized sender alias.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalpendingenrollment',
            name='cohort_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalpendingenrollment',
            name='license_uuid',
            field=models.UUIDField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='historicalpendingenrollment',
            name='sales_force_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pendingenrollment',
            name='cohort_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pendingenrollment',
            name='license_uuid',
            field=models.UUIDField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='pendingenrollment',
            name='sales_force_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
