# Generated by Django 3.2.17 on 2023-02-21 18:35

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    licensed_enrollments = apps.get_model('enterprise', 'LicensedEnterpriseCourseEnrollment')
    for licensed_enrollment in licensed_enrollments.objects.all():
        licensed_enrollment.uuid = uuid.uuid4()
        licensed_enrollment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0167_auto_20230209_2108'),
    ]

    operations = [
        migrations.RunPython(create_uuid, reverse_code=migrations.RunPython.noop),

    ]
