# Generated by Django 3.2.19 on 2023-07-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0174_auto_20230608_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomer',
            name='hide_course_price_when_zero',
            field=models.BooleanField(default=False, help_text="Hides the course's price from the enrollment page when it is Zero, either by itself or due to a discount."),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomer',
            name='hide_course_price_when_zero',
            field=models.BooleanField(default=False, help_text="Hides the course's price from the enrollment page when it is Zero, either by itself or due to a discount."),
        ),
    ]
