# Generated by Django 3.2.19 on 2023-06-29 13:39

from django.db import migrations, models
import django.db.models.deletion
import enterprise.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('enterprise', '0176_auto_20230628_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisecustomer',
            name='site',
            field=models.ForeignKey(default=enterprise.models.EnterpriseCustomer.get_default_site, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_customers', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='historicalenterprisecustomer',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, default=enterprise.models.EnterpriseCustomer.get_default_site, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site'),
        ),
    ]
