# Generated by Django 3.2.19 on 2023-07-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0176_auto_20230712_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisecustomer',
            name='auth_org_id',
            field=models.CharField(blank=True, help_text='Enterprise customer auth organization ID ', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisecustomer',
            name='enable_executive_education_2U_fulfillment',
            field=models.BooleanField(default=False, help_text='Specifies whether the organization should have access to executive education 2U content.'),
        ),
        migrations.AlterField(
            model_name='historicalenterprisecustomer',
            name='auth_org_id',
            field=models.CharField(blank=True, help_text='Enterprise customer auth organization ID ', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='historicalenterprisecustomer',
            name='enable_executive_education_2U_fulfillment',
            field=models.BooleanField(default=False, help_text='Specifies whether the organization should have access to executive education 2U content.'),
        ),
    ]
