# Generated by Django 3.2.20 on 2023-08-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0177_auto_20230712_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomer',
            name='allow_enrollment_in_invite_only_courses',
            field=models.BooleanField(default=False, help_text="Specifies if learners are allowed to enroll into courses marked as 'invitation-only', when they attempt to enroll from the landing page."),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomer',
            name='allow_enrollment_in_invite_only_courses',
            field=models.BooleanField(default=False, help_text="Specifies if learners are allowed to enroll into courses marked as 'invitation-only', when they attempt to enroll from the landing page."),
        ),
    ]
