# Generated by Django 3.2.20 on 2023-08-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0178_auto_20230808_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalenrollmentnotificationemailtemplate',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical enrollment notification email template'},
        ),
        migrations.AlterModelOptions(
            name='historicalenterprisecourseenrollment',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical enterprise course enrollment'},
        ),
        migrations.AlterModelOptions(
            name='historicalenterprisecourseentitlement',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical enterprise course entitlement'},
        ),
        migrations.AlterModelOptions(
            name='historicalenterprisecustomer',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Enterprise Customer'},
        ),
        migrations.AlterModelOptions(
            name='historicalenterprisecustomercatalog',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Enterprise Customer Catalog'},
        ),
        migrations.AlterModelOptions(
            name='historicalenterprisecustomerinvitekey',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical enterprise customer invite key'},
        ),
        migrations.AlterModelOptions(
            name='historicalenterprisecustomeruser',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Enterprise Customer Learner'},
        ),
        migrations.AlterModelOptions(
            name='historicallearnercreditenterprisecourseenrollment',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical learner credit enterprise course enrollment'},
        ),
        migrations.AlterModelOptions(
            name='historicallicensedenterprisecourseenrollment',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical licensed enterprise course enrollment'},
        ),
        migrations.AlterModelOptions(
            name='historicalpendingenrollment',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical pending enrollment'},
        ),
        migrations.AlterModelOptions(
            name='historicalpendingenterprisecustomeradminuser',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical pending enterprise customer admin user'},
        ),
        migrations.AlterModelOptions(
            name='historicalpendingenterprisecustomeruser',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical pending enterprise customer user'},
        ),
        migrations.AlterModelOptions(
            name='historicalsystemwideenterpriseuserroleassignment',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical system wide enterprise user role assignment'},
        ),
        migrations.AddField(
            model_name='enterprisecustomer',
            name='enable_generation_of_api_credentials',
            field=models.BooleanField(default=False, verbose_name='Allow generation of API credentials'),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomer',
            name='enable_generation_of_api_credentials',
            field=models.BooleanField(default=False, verbose_name='Allow generation of API credentials'),
        ),
    ]
