# Generated by Django 3.2.23 on 2023-12-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0197_auto_20231130_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomer',
            name='hide_course_price_when_zero',
            field=models.BooleanField(default=False, help_text='Specify whether course cost should be hidden in the landing page when the final price is zero.'),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomer',
            name='hide_course_price_when_zero',
            field=models.BooleanField(default=False, help_text='Specify whether course cost should be hidden in the landing page when the final price is zero.'),
        ),
    ]
