# Generated by Django 4.2.10 on 2024-06-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0209_alter_enterprisecustomer_disable_expiry_messaging_for_learner_credit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprisecustomer',
            old_name='career_engagement_network_message',
            new_name='learner_portal_sidebar_content',
        ),
        migrations.RenameField(
            model_name='enterprisecustomer',
            old_name='enable_career_engagement_network_on_learner_portal',
            new_name='enable_learner_portal_sidebar_message',
        ),
        migrations.RenameField(
            model_name='historicalenterprisecustomer',
            old_name='career_engagement_network_message',
            new_name='learner_portal_sidebar_content',
        ),
        migrations.RenameField(
            model_name='historicalenterprisecustomer',
            old_name='enable_career_engagement_network_on_learner_portal',
            new_name='enable_learner_portal_sidebar_message',
        ),
    ]
