# Generated by Django 4.2.10 on 2024-06-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0210_remove_enterprisecustomer_career_engagement_network_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisecustomer',
            name='enable_learner_portal_sidebar_message',
            field=models.BooleanField(default=False, help_text='If checked, learners will be able to see content in the Learner Portal Sidebar found in the HTML box.', verbose_name='Enable learner portal sidebar message'),
        ),
        migrations.AlterField(
            model_name='enterprisecustomer',
            name='learner_portal_sidebar_content',
            field=models.TextField(blank=True, help_text='Text shown on the learner portal dashboard for customer specific purposes. Open HTML field.'),
        ),
        migrations.AlterField(
            model_name='historicalenterprisecustomer',
            name='enable_learner_portal_sidebar_message',
            field=models.BooleanField(default=False, help_text='If checked, learners will be able to see content in the Learner Portal Sidebar found in the HTML box.', verbose_name='Enable learner portal sidebar message'),
        ),
        migrations.AlterField(
            model_name='historicalenterprisecustomer',
            name='learner_portal_sidebar_content',
            field=models.TextField(blank=True, help_text='Text shown on the learner portal dashboard for customer specific purposes. Open HTML field.'),
        ),
    ]
