# Generated by Django 4.2.10 on 2024-06-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0210_enterprisecustomer_enable_learner_portal_sidebar_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisecustomer',
            name='career_engagement_network_message',
            field=models.TextField(blank=True, help_text='Message text shown on the learner portal dashboard for career engagement network.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalenterprisecustomer',
            name='career_engagement_network_message',
            field=models.TextField(blank=True, help_text='Message text shown on the learner portal dashboard for career engagement network.', null=True),
        ),
    ]
