# Generated by Django 4.2.16 on 2024-10-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0223_default_enrollments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprisegroup',
            name='applies_to_all_contexts',
        ),
        migrations.RemoveField(
            model_name='historicalenterprisegroup',
            name='applies_to_all_contexts',
        ),
    ]
