# Generated by Django 4.2.18 on 2025-02-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0228_alter_defaultenterpriseenrollmentrealization_realized_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomer',
            name='salesforce_customer_record_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SalesForce Customer Record ID'),
        ),
        migrations.AddField(
            model_name='enterprisecustomer',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Populated if this customer purchased through Stripe.', max_length=255, null=True, verbose_name='Stripe Customer ID'),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomer',
            name='salesforce_customer_record_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SalesForce Customer Record ID'),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomer',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Populated if this customer purchased through Stripe.', max_length=255, null=True, verbose_name='Stripe Customer ID'),
        ),
    ]
