# Generated by Django 4.2.16 on 2025-02-14 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprise', '0228_alter_defaultenterpriseenrollmentrealization_realized_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomeruser',
            name='user_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_customer_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomeruser',
            name='user_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
