# Generated by Django 4.2.19 on 2025-04-25 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprise', '0233_onboardingflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseCustomerAdmin',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(blank=True, help_text='The last time the admin logged into the admin portal.', null=True)),
                ('onboarding_tour_dismissed', models.BooleanField(default=False, help_text='Whether the admin has dismissed the onboarding tour.')),
                ('onboarding_tour_completed', models.BooleanField(default=False, help_text='Whether the admin has completed the onboarding tour.')),
            ],
            options={
                'verbose_name': 'Enterprise Customer Admin',
                'verbose_name_plural': 'Enterprise Customer Admins',
                'ordering': ['-modified'],
            },
        ),
        migrations.AlterField(
            model_name='enterprisecustomeruser',
            name='user_fk',
            field=models.ForeignKey(db_column='user_fk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_customer_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalenterprisecustomeruser',
            name='user_fk',
            field=models.ForeignKey(blank=True, db_column='user_fk', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='enterprisecustomeruser',
            index=models.Index(fields=['user_fk'], name='idx_enterprise_user_fk'),
        ),
        migrations.AddField(
            model_name='enterprisecustomeradmin',
            name='completed_tour_flows',
            field=models.ManyToManyField(blank=True, help_text='The onboarding flows that this admin has completed.', to='enterprise.onboardingflow'),
        ),
        migrations.AddField(
            model_name='enterprisecustomeradmin',
            name='enterprise_customer_user',
            field=models.ForeignKey(help_text='The enterprise customer user who is an admin.', on_delete=django.db.models.deletion.CASCADE, related_name='admin_records', to='enterprise.enterprisecustomeruser'),
        ),
    ]
