# Generated by Django 4.2.20 on 2025-05-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0237_enterprisecustomersupportusersview'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomer',
            name='enable_learner_credit_modal',
            field=models.BooleanField(default=True, verbose_name='Display learner credit modal in learner portal'),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomer',
            name='enable_learner_credit_modal',
            field=models.BooleanField(default=True, verbose_name='Display learner credit modal in learner portal'),
        ),
    ]
