# Generated by Django 4.2.20 on 2025-05-21 04:50

from django.db import migrations

def backfill_enable_learner_credit_modal(apps, schema_editor):
    """
    Backfill enable_learner_credit_modal field for all existing EnterpriseCustomer records.
    """
    EnterpriseCustomer = apps.get_model('enterprise', 'EnterpriseCustomer')
    EnterpriseCustomer.objects.all().update(enable_learner_credit_modal=True)

class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0238_enterprisecustomer_enable_learner_credit_modal_and_more'),
    ]

    operations = [
        migrations.RunPython(
            backfill_enable_learner_credit_modal,
            reverse_code=migrations.RunPython.noop
        ),
    ]
