# Generated by Django 4.2.22 on 2025-06-12 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.WAFFLE_FLAG_MODEL),
        ('enterprise', '0240_alter_enterprisecustomer_enable_data_sharing_consent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseWaffleFlagPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('percent', models.DecimalField(decimal_places=1, default='0.0', help_text='Activate this flag for this percentage of users within this enterprise. Overrides the global flag percentage.', max_digits=4, verbose_name='Percentage')),
                ('enterprise_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waffle_flag_percentages', to='enterprise.enterprisecustomer')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_percentages', to=settings.WAFFLE_FLAG_MODEL)),
            ],
            options={
                'verbose_name': 'Enterprise Waffle Flag Percentage',
                'verbose_name_plural': 'Enterprise Waffle Flag Percentages',
                'unique_together': {('flag', 'enterprise_customer')},
            },
        ),
    ]
