# Generated by Django 5.2.8 on 2026-01-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0242_mariadb_uuid_conversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprisecustomeradmin",
            name="joined_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the admin accepted the invite and was created.",
                null=True,
            ),
        ),
    ]
