# Generated by Django 5.2.8 on 2026-02-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0242_mariadb_uuid_conversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprisecustomeradmin",
            name="invited_date",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time when the admin was invited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprisecustomeradmin",
            name="joined_date",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time when the admin joined/registered their account.",
                null=True,
            ),
        ),
    ]
