# Generated by Django 5.2.8 on 2025-12-16 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0242_mariadb_uuid_conversion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprisecustomeruser",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin user who sent the invitation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enterprise_users_invited",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enterprisecustomeruser",
            name="invited_date",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when the user was invited.", null=True
            ),
        ),
        migrations.AddField(
            model_name="enterprisecustomeruser",
            name="joined_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the user accepted the invite / joined.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalenterprisecustomeruser",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Admin user who sent the invitation.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalenterprisecustomeruser",
            name="invited_date",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when the user was invited.", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalenterprisecustomeruser",
            name="joined_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the user accepted the invite / joined.",
                null=True,
            ),
        ),
    ]
