# Generated by Django 5.2.12 on 2026-04-07 11:19

import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0243_add_reminder_sent_at_to_pending_admin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnterpriseAcademy",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Short identifier name for the Academy (e.g. "AI Academy").',
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "long_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Full display name of the Academy.",
                        max_length=512,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Marketing description of the Academy.",
                    ),
                ),
                (
                    "marketing_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Public-facing marketing URL for the Academy landing page.",
                        max_length=2048,
                    ),
                ),
                (
                    "thumbnail_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Relative S3 path (or absolute URL) for the Academy thumbnail image. If storing a relative path, the S3 bucket base URL is configured via settings.ACADEMY_THUMBNAIL_S3_BASE_URL.",
                        max_length=2048,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Display price for the Academy, synced from Stripe. Stripe (stripe_product_id) is the authoritative source for billing.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "tags",
                    jsonfield.fields.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON array of tag strings associated with this Academy.",
                    ),
                ),
                (
                    "stripe_product_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Stripe Product ID for this Academy. Stripe is the single source of truth for pricing and entitlements.",
                        max_length=255,
                    ),
                ),
                (
                    "stripe_price_lookup_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Stripe price lookup_key declared in Terraform. Used by the BFF pricing context to resolve prices by academy selection.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "edx_catalog_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID of the associated Enterprise Catalog (from the enterprise-catalog service) that defines the content available in this Academy.",
                        null=True,
                    ),
                ),
                (
                    "product_key",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Routing key matching the ?product_key= query param from business.edx.org. Used to identify which academy the user selected at checkout entry.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Stable URL-safe slug for academy detail API routes.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Controls whether this academy is visible in public API responses. Set to False to retire an academy without deleting it.",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Ascending sort order for academy list API responses.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academy",
                "verbose_name_plural": "Academies",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEnterpriseAcademy",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text='Short identifier name for the Academy (e.g. "AI Academy").',
                        max_length=255,
                    ),
                ),
                (
                    "long_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Full display name of the Academy.",
                        max_length=512,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Marketing description of the Academy.",
                    ),
                ),
                (
                    "marketing_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Public-facing marketing URL for the Academy landing page.",
                        max_length=2048,
                    ),
                ),
                (
                    "thumbnail_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Relative S3 path (or absolute URL) for the Academy thumbnail image. If storing a relative path, the S3 bucket base URL is configured via settings.ACADEMY_THUMBNAIL_S3_BASE_URL.",
                        max_length=2048,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Display price for the Academy, synced from Stripe. Stripe (stripe_product_id) is the authoritative source for billing.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "tags",
                    jsonfield.fields.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON array of tag strings associated with this Academy.",
                    ),
                ),
                (
                    "stripe_product_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Stripe Product ID for this Academy. Stripe is the single source of truth for pricing and entitlements.",
                        max_length=255,
                    ),
                ),
                (
                    "stripe_price_lookup_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Stripe price lookup_key declared in Terraform. Used by the BFF pricing context to resolve prices by academy selection.",
                        max_length=255,
                    ),
                ),
                (
                    "edx_catalog_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID of the associated Enterprise Catalog (from the enterprise-catalog service) that defines the content available in this Academy.",
                        null=True,
                    ),
                ),
                (
                    "product_key",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Routing key matching the ?product_key= query param from business.edx.org. Used to identify which academy the user selected at checkout entry.",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Stable URL-safe slug for academy detail API routes.",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Controls whether this academy is visible in public API responses. Set to False to retire an academy without deleting it.",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Ascending sort order for academy list API responses.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Academy",
                "verbose_name_plural": "historical Academies",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
