# Generated by Django 4.2.30 on 2026-08-28 05:26

import collections
from django.db import migrations, models
import enterprise.validators
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0251_add_non_production_customer_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprisecustomer",
            name="enable_demo_data_for_analytics_and_lpr",
            field=models.BooleanField(
                default=False,
                help_text="Display demo data from analytics and the learner progress report for demo customers. Dummy data will only appear if the enterprise user is also registered as an admin on the analytics demo portal. Contact the support team or use Django admin to set this up.",
                verbose_name="Enable demo data from analytics and lpr",
            ),
        ),
        migrations.AlterField(
            model_name="enterprisecustomercatalog",
            name="content_filter",
            field=jsonfield.fields.JSONField(
                blank=True,
                default={},
                dump_kwargs={
                    "cls": jsonfield.encoder.JSONEncoder,
                    "indent": 4,
                    "separators": (",", ":"),
                },
                help_text="Query parameters which will be used to filter the discovery service's search/all endpoint results, specified as a Json object. An empty Json object means that all available content items will be included in the catalog.",
                load_kwargs={"object_pairs_hook": collections.OrderedDict},
                null=True,
                validators=[enterprise.validators.validate_content_filter_fields],
            ),
        ),
        migrations.AlterField(
            model_name="historicalenterprisecustomer",
            name="enable_demo_data_for_analytics_and_lpr",
            field=models.BooleanField(
                default=False,
                help_text="Display demo data from analytics and the learner progress report for demo customers. Dummy data will only appear if the enterprise user is also registered as an admin on the analytics demo portal. Contact the support team or use Django admin to set this up.",
                verbose_name="Enable demo data from analytics and lpr",
            ),
        ),
        migrations.AlterField(
            model_name="historicalenterprisecustomercatalog",
            name="content_filter",
            field=jsonfield.fields.JSONField(
                blank=True,
                default={},
                dump_kwargs={
                    "cls": jsonfield.encoder.JSONEncoder,
                    "indent": 4,
                    "separators": (",", ":"),
                },
                help_text="Query parameters which will be used to filter the discovery service's search/all endpoint results, specified as a Json object. An empty Json object means that all available content items will be included in the catalog.",
                load_kwargs={"object_pairs_hook": collections.OrderedDict},
                null=True,
                validators=[enterprise.validators.validate_content_filter_fields],
            ),
        ),
    ]
