version: 2
updates:
  # Ensure all GitHub Actions are up-to-date.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Disable any org-level dependabot settings for "pip" packages.
  # This library does not need automatic python package updates, and
  # furthermore it is detrimental to staying synchronized with upstream
  # openedx-platform.
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0  # This disables all PRs for pip updates
