# This is a Code Annotations automatically-generated Django model safelist file.
# These models must be annotated as follows in order to be counted in the coverage report.
# See https://code-annotations.readthedocs.io/en/latest/safelist.html for more information.
#
# fake_app_1.FakeModelName:
#    ".. no_pii:": "This model has no PII"
# fake_app_2.FakeModel2:
#    ".. choice_annotation:": foo, bar, baz

canvas.HistoricalCanvasEnterpriseCustomerConfiguration:
  ".. no_pii:": ""
consent.HistoricalDataSharingConsent:
  ".. pii:": "The username field inherited from DataSharingConsent contains PII"
  ".. pii_types:": username
  ".. pii_retirement:": consumer_api
degreed.HistoricalDegreedEnterpriseCustomerConfiguration:
  ".. no_pii:": ""
enterprise.HistoricalDefaultEnterpriseEnrollmentIntention:
  ".. no_pii:": ""
enterprise.HistoricalDefaultEnterpriseEnrollmentRealization:
  ".. no_pii:": ""
enterprise.HistoricalEnrollmentNotificationEmailTemplate:
  ".. no_pii:": ""
enterprise.HistoricalEnterpriseCourseEnrollment:
  ".. no_pii:": ""
enterprise.HistoricalEnterpriseCustomer:
  ".. no_pii:": ""
enterprise.HistoricalEnterpriseCustomerCatalog:
  ".. no_pii:": ""
enterprise.HistoricalEnterpriseCustomerEntitlement:
  ".. no_pii:": ""
enterprise.HistoricalEnterpriseAnalyticsUser:
  ".. no_pii:": ""
enterprise.HistoricalPendingEnterpriseCustomerUser:
  ".. no_pii:": ""
enterprise.HistoricalPendingEnterpriseCustomerAdminUser:
  ".. no_pii:": ""
enterprise.HistoricalLicensedEnterpriseCourseEnrollment:
  ".. no_pii:": ""
enterprise.HistoricalPendingEnrollment:
  ".. no_pii:": ""
moodle.HistoricalMoodleEnterpriseCustomerConfiguration:
  ".. no_pii:": ""
enterprise.HistoricalEnterpriseCourseEntitlement:
  ".. no_pii:": ""
enterprise.HistoricalEnterpriseCustomerInviteKey:
  ".. no_pii:": ""
enterprise.HistoricalEnterpriseCustomerSsoConfiguration:
  ".. no_pii:": ""
enterprise.HistoricalEnterpriseCustomerUser:
  ".. no_pii:": ""
enterprise.HistoricalEnterpriseGroup:
  ".. no_pii:": ""
enterprise.HistoricalEnterpriseGroupMembership:
  ".. no_pii:": ""
enterprise.HistoricalLearnerCreditEnterpriseCourseEnrollment:
  ".. no_pii:": ""
enterprise.HistoricalSystemWideEnterpriseUserRoleAssignment:
  ".. no_pii:": ""
