# Standard settings used by CI and Makefile targets.
#
# Designed to run all tests and produce comprehensive coverage reporting.
#
# Example usage:
# ```
# pytest
# ```
[pytest]
DJANGO_SETTINGS_MODULE = enterprise.settings.test
addopts = --cov enterprise --cov enterprise_learner_portal --cov consent --cov integrated_channels --cov-report term-missing --cov-report xml
norecursedirs = .* docs requirements site-packages scripts node_modules
testpaths = tests
