[tox]
envlist = py{312}-django{52}
requires =
    tox-uv>=1

[doc8]
max-line-length = 120

[wheel]
universal = 1

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    test
setenv =
    TOXENV={envname}
deps =
    django52: Django>=5.2,<5.3
commands =
    py.test -Wd {posargs}

[testenv:docs]
runner = uv-venv-lock-runner
dependency_groups =
    doc
setenv =
    DJANGO_SETTINGS_MODULE = enterprise.settings.test
    PYTHONPATH = {toxinidir}
allowlist_externals =
    make
    rm
commands =
    doc8 --ignore-path docs/_build --ignore-path docs/decisions README.rst docs
    rm -f docs/enterprise.rst
    rm -f docs/modules.rst
    make -C docs clean
    make -C docs html
    python -m build --wheel
    twine check dist/*

[testenv:isort]
runner = uv-venv-lock-runner
dependency_groups =
    dev
commands =
    isort --skip migrations tests test_utils enterprise enterprise_learner_portal consent integrated_channels manage.py

[testenv:isort-check]
runner = uv-venv-lock-runner
dependency_groups =
    dev
commands =
    isort --skip migrations --check-only --diff tests test_utils enterprise enterprise_learner_portal consent integrated_channels manage.py

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups =
    dev
setenv =
    DJANGO_SETTINGS_MODULE = enterprise.settings.test
allowlist_externals =
    rm
    touch
commands =
    touch tests/__init__.py
    pylint -j 1 enterprise enterprise_learner_portal --clear-cache-post-run=y
    pylint -j 1 consent integrated_channels --clear-cache-post-run=y
    pylint -j 1 test_utils requirements/sync_platform_constraints.py --clear-cache-post-run=y
    pylint -j 1 tests -v --clear-cache-post-run=y
    rm tests/__init__.py
    pycodestyle enterprise enterprise_learner_portal consent integrated_channels tests test_utils
    isort --skip migrations --check-only --diff tests test_utils enterprise enterprise_learner_portal consent integrated_channels manage.py

[testenv:jasmine]
runner = uv-venv-lock-runner
dependency_groups =
    js_test
passenv = JASMINE_BROWSER DISPLAY
commands =
    jasmine

[testenv:pii_check]
runner = uv-venv-lock-runner
dependency_groups =
    test
setenv =
    DJANGO_SETTINGS_MODULE = enterprise.settings.test
commands =
    code_annotations django_find_annotations --config_file .pii_annotations.yml --lint --report --coverage
