# Generated by Django 3.2.12 on 2022-05-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_success_factors', '0004_auto_20220324_1550_squashed_0006_auto_20220330_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapsuccessfactorsenterprisecustomerconfiguration',
            name='dry_run_mode_enabled',
            field=models.BooleanField(default=False, help_text='Is this configuration in dry-run mode? (experimental)'),
        ),
    ]
