# Generated by Django 4.2.13 on 2024-05-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0034_delete_historicalcanvasenterprisecustomerconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvaslearnerassessmentdatatransmissionaudit',
            name='is_transmitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canvaslearnerdatatransmissionaudit',
            name='is_transmitted',
            field=models.BooleanField(default=False),
        ),
    ]
