# Generated by Django 3.2.11 on 2022-01-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrated_channel', '0006_contentmetadataitemtransmission_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmetadataitemtransmission',
            name='enterprise_customer_catalog_uuid',
            field=models.UUIDField(blank=True, default='', help_text='The enterprise catalog that this metadata item was derived from'),
        ),
        migrations.AlterField(
            model_name='learnerdatatransmissionaudit',
            name='subsection_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
