# Generated by Django 3.2.20 on 2023-11-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrated_channel', '0029_genericenterprisecustomerpluginconfiguration_show_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericenterprisecustomerpluginconfiguration',
            name='enable_incomplete_progress_transmission',
            field=models.BooleanField(default=True, help_text='When set to True, the configured customer will receive learner data transmissions, for incomplete courses as well'),
        ),
    ]
