# Generated by Django 3.2.23 on 2024-01-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrated_channel', '0030_integratedchannelapirequestlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericlearnerdatatransmissionaudit',
            name='transmission_status',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
