# Generated by Django 3.2.22 on 2024-01-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrated_channel', '0030_integratedchannelapirequestlogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integratedchannelapirequestlogs',
            options={'verbose_name_plural': 'Integrated channels API request logs'},
        ),
    ]
