# Generated by Django 3.2.23 on 2024-01-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrated_channel', '0030_integratedchannelapirequestlogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integratedchannelapirequestlogs',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='integratedchannelapirequestlogs',
            name='user_ip',
        ),
    ]
