# Generated by Django 3.2.22 on 2024-01-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrated_channel', '0031_genericlearnerdatatransmissionaudit_transmission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericlearnerdatatransmissionaudit',
            name='transmission_status',
        ),
    ]
