# Generated by Django 3.2.23 on 2024-01-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrated_channel', '0031_genericlearnerdatatransmissionaudit_transmission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integratedchannelapirequestlogs',
            name='api_record',
        ),
        migrations.AddField(
            model_name='integratedchannelapirequestlogs',
            name='response_body',
            field=models.TextField(blank=True, help_text='TAPI call response body', null=True),
        ),
        migrations.AddField(
            model_name='integratedchannelapirequestlogs',
            name='status_code',
            field=models.PositiveIntegerField(blank=True, help_text='API call response HTTP status code', null=True),
        ),
    ]
