# Generated by Django 3.2.23 on 2024-03-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrated_channel', '0033_integratedchannelapirequestlogs_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integratedchannelapirequestlogs',
            name='channel_name',
            field=models.CharField(blank=True, choices=[('MOODLE', 'MOODLE'), ('DEGREED2', 'DEGREED2'), ('CANVAS', 'CANVAS'), ('SAP', 'SAP SUCCESS FACTORS'), ('CSOD', 'CORNERSTONE'), ('BLACKBOARD', 'BLACKBOARD')], help_text='Name of the integrated channel associated with this API call log record.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='integratedchannelapirequestlogs',
            index=models.Index(fields=['channel_name', 'status_code', 'enterprise_customer_configuration_id', 'endpoint'], name='integrated__channel_a3b90f_idx'),
        ),
    ]
