# Generated by Django 3.2.19 on 2024-03-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrated_channel', '0034_contentmetadataitemtransmission_remote_errored_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericlearnerdatatransmissionaudit',
            name='enterprise_course_enrollment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
