"""
Miscellaneous utils for tests.
"""
import copy
from collections import namedtuple

from django.utils import timezone


def merge_dicts(dict1, dict2):
    """
    Merge dict1 and dict2 and returns merged dict.

    If dict2 has a key with value set to `undefined` it removes that key from dict1
    """
    merged_dict = copy.deepcopy(dict1)
    if dict2:
        for key, val in dict2.items():
            if val == 'undefined' and key in merged_dict:
                del merged_dict[key]
            else:
                merged_dict.update(dict2)
    return merged_dict


def mock_course_overview(display_name='Course Title', pacing='instructor', end=timezone.now()):
    """Generate an object approximating the CourseOverview model from edx-platform"""
    dictionary = {
        'end': end,
        'pacing': pacing,
        'display_name': display_name,
    }
    return namedtuple("CourseOverview", dictionary.keys())(*dictionary.values())


def mock_single_learner_grade(percent=0.0, passing=False):
    """Generate an object matching the CourseGrade generated by CourseGradeFactory().read"""
    dictionary = {
        'percent': percent,
        'passed': passing,
    }
    return namedtuple("CourseGrade", dictionary.keys())(*dictionary.values())


def mock_persistent_course_grade(user_id, course_id, passed_timestamp):
    """Generate an object matching the PersistentCourseGrade from edx-platform"""
    dictionary = {
        'user_id': user_id,
        'course_id': course_id,
        'passed_timestamp': passed_timestamp,
    }
    return namedtuple("PersistentCourseGrade", dictionary.keys())(*dictionary.values())
