# Generated by Django 2.2.16 on 2020-10-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0002_auto_20200930_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackboardLearnerDataTransmissionAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blackboard_user_email', models.EmailField(help_text='The learner`s Blackboard email. This must match the email on edX in order for both learner and content metadata integrations.', max_length=255)),
                ('completed_timestamp', models.CharField(help_text='Represents the Blackboard representation of a timestamp: yyyy-mm-dd, which is always 10 characters.', max_length=10)),
                ('course_id', models.CharField(max_length=255)),
                ('course_completed', models.BooleanField(default=True, help_text="The learner's course completion status transmitted to Blackboard.")),
                ('enterprise_course_enrollment_id', models.PositiveIntegerField(db_index=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('total_hours', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
