# Generated by Django 3.2.11 on 2022-01-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0010_auto_20211221_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackboardlearnerassessmentdatatransmissionaudit',
            name='enterprise_course_enrollment_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
