# Generated by Django 3.2.15 on 2022-12-20 15:05

from django.db import connection, migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('blackboard', '0012_move_and_recrete_completed_timestamp'),
    ]

    db_engine = connection.settings_dict['ENGINE']
    if 'sqlite3' in db_engine:
        operations = [
            migrations.AlterIndexTogether(
                name='blackboardlearnerdatatransmissionaudit',
                index_together={('enterprise_customer_uuid', 'plugin_configuration_id')},
            ),
        ]
    else:
        operations = [
            migrations.SeparateDatabaseAndState(
                state_operations=[
                    migrations.AlterIndexTogether(
                        name='blackboardlearnerdatatransmissionaudit',
                        index_together={('enterprise_customer_uuid', 'plugin_configuration_id')},
                    ),
                ],
                database_operations=[
                    migrations.RunSQL(sql="""
                        CREATE INDEX blackboard_bldta_85936b55_idx
                        ON blackboard_blackboardlearnerdatatransmissionaudit (enterprise_customer_uuid, plugin_configuration_id)
                        ALGORITHM=INPLACE LOCK=NONE
                    """, reverse_sql="""
                        DROP INDEX blackboard_bldta_85936b55_idx
                        ON blackboard_blackboardlearnerdatatransmissionaudit
                    """),
                ]
            ),
        ]
