# Generated by Django 3.2.19 on 2023-07-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0016_auto_20230719_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalblackboardenterprisecustomerconfiguration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical blackboard enterprise customer configuration', 'verbose_name_plural': 'historical blackboard enterprise customer configurations'},
        ),
    ]
