# Generated by Django 3.2.23 on 2024-01-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0017_alter_historicalblackboardenterprisecustomerconfiguration_options'),
    ]

    # johnnagro 20240118 DOS-4490
    # Making this migration a no-op to revert a partially applied deploy migration
    # operations = [
    #     migrations.AddField(
    #         model_name='blackboardlearnerassessmentdatatransmissionaudit',
    #         name='transmission_status',
    #         field=models.JSONField(blank=True, default=list, null=True),
    #     ),
    #     migrations.AddField(
    #         model_name='blackboardlearnerdatatransmissionaudit',
    #         name='transmission_status',
    #         field=models.JSONField(blank=True, default=list, null=True),
    #     ),
    # ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, reverse_code=migrations.RunPython.noop)
    ]
