# Generated by Django 3.2.22 on 2024-01-18 18:22

from django.apps import apps
from django.db import migrations
from django.core.exceptions import FieldDoesNotExist


class Migration(migrations.Migration): 

    dependencies = [
        ('blackboard', '0018_auto_20240110_1301'),
    ]

    # johnnagro 20240118 DOS-4490
    # we are reverting a partially applied deployment migration
    # this migration conditionally cleans up the previous migration operations
    # only if they were part of the partially applied ones

    BlackboardLearnerAssessmentDataTransmissionAudit = apps.get_model('blackboard', 'BlackboardLearnerAssessmentDataTransmissionAudit')
    BlackboardLearnerDataTransmissionAudit = apps.get_model('blackboard', 'BlackboardLearnerDataTransmissionAudit')

    operations = []

    try:
        if BlackboardLearnerDataTransmissionAudit._meta.get_field('transmission_status'):
            operations.append(
                migrations.RemoveField(
                    model_name='blackboardlearnerdatatransmissionaudit',
                    name='transmission_status',
                )
            )
    except FieldDoesNotExist:
        pass

    try:
        if BlackboardLearnerAssessmentDataTransmissionAudit._meta.get_field('transmission_status'):
            operations.append(
                migrations.RemoveField(
                    model_name='blackboardlearnerassessmentdatatransmissionaudit',
                    name='transmission_status',
                )
            )
    except FieldDoesNotExist:
        pass
