# Generated by Django 3.2.22 on 2024-01-18 18:22

from django.db import migrations
from django.core.exceptions import FieldDoesNotExist
from integrated_channels.blackboard.models import *


def forwards_func(apps, schema_editor):
    try:
        if field := BlackboardLearnerDataTransmissionAudit._meta.get_field('transmission_status'):            
            schema_editor.remove_field(BlackboardLearnerDataTransmissionAudit, field)
    except FieldDoesNotExist:
        pass
    
    try:
        if field := BlackboardLearnerAssessmentDataTransmissionAudit._meta.get_field('transmission_status'):
            schema_editor.remove_field(BlackboardLearnerAssessmentDataTransmissionAudit, field)
    except FieldDoesNotExist:
        pass


class Migration(migrations.Migration): 

    dependencies = [
        ('blackboard', '0018_auto_20240110_1301'),
    ]

    # johnnagro 20240118 DOS-4490
    # we are reverting a partially applied deployment migration
    # this migration conditionally cleans up the previous migration operations
    # only if they were part of the partially applied ones

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop)
    ]
