# Generated by Django 3.2.19 on 2024-03-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0019_delete_historicalblackboardenterprisecustomerconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackboardlearnerassessmentdatatransmissionaudit',
            name='enterprise_course_enrollment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blackboardlearnerdatatransmissionaudit',
            name='enterprise_course_enrollment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='blackboardlearnerdatatransmissionaudit',
            index=models.Index(fields=['error_message', 'enterprise_course_enrollment_id'], name='blackboard_course_error_idx'),
        ),
    ]
