# Generated by Django 3.2.23 on 2024-04-23 10:57

from django.db import migrations


def populate_decrypted_fields(apps, schema_editor):
    """
    Populates the encryption fields with the data previously stored in database.
    """
    BlackboardEnterpriseCustomerConfiguration = apps.get_model('blackboard', 'BlackboardEnterpriseCustomerConfiguration')

    for blackboard_enterprise_configuration in BlackboardEnterpriseCustomerConfiguration.objects.all():
        blackboard_enterprise_configuration.decrypted_client_id = blackboard_enterprise_configuration.client_id
        blackboard_enterprise_configuration.decrypted_client_secret = blackboard_enterprise_configuration.client_secret
        blackboard_enterprise_configuration.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0020_auto_20240422_1709'),
    ]

    operations = [
        migrations.RunPython(populate_decrypted_fields, reverse_code=migrations.RunPython.noop),
    ]
