# Generated by Django 3.2.23 on 2024-06-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0023_auto_20240605_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blackboardenterprisecustomerconfiguration',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='blackboardenterprisecustomerconfiguration',
            name='client_secret',
        ),
    ]
