# Generated by Django 4.2.21 on 2025-05-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0023_auto_20240604_1046'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blackboardlearnerdatatransmissionaudit',
            new_name='blackboard_customer_plugin_idx',
            old_fields=('enterprise_customer_uuid', 'plugin_configuration_id'),
        ),
    ]
