# Generated by Django 3.2.22 on 2024-02-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0017_alter_historicalblackboardenterprisecustomerconfiguration_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='blackboardlearnerdatatransmissionaudit',
            constraint=models.UniqueConstraint(fields=('enterprise_course_enrollment_id', 'course_id'), name='blackboard_unique_enrollment_course_id'),
        ),
    ]
