# Generated by Django 3.2.19 on 2024-02-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0018_blackboardlearnerdatatransmissionaudit_blackboard_unique_enrollment_course_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalBlackboardEnterpriseCustomerConfiguration',
        ),
    ]
