# Generated by Django 4.2.21 on 2025-05-19 17:15

from django.db import migrations, connection


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0023_auto_20240604_1046'),
    ]

    database_operations = []
    if connection.vendor != 'sqlite':
        database_operations.append(
            migrations.RenameIndex(
                model_name='blackboardlearnerdatatransmissionaudit',
                old_fields=('enterprise_customer_uuid', 'plugin_configuration_id'),
                new_name='blackboard_customer_plugin_idx',
            )
        )

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=[
                migrations.RenameIndex(
                    model_name='blackboardlearnerdatatransmissionaudit',
                    old_fields=('enterprise_customer_uuid', 'plugin_configuration_id'),
                    new_name='blackboard_customer_plugin_idx',
                ),
            ],
        )
    ]
