# Generated by Django 3.2.12 on 2022-03-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0004_auto_20190830_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='xapilearnerdatatransmissionaudit',
            name='enterprise_customer_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xapilearnerdatatransmissionaudit',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='xapilearnerdatatransmissionaudit',
            name='plugin_configuration_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xapilearnerdatatransmissionaudit',
            name='total_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xapilearnerdatatransmissionaudit',
            name='course_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='xapilearnerdatatransmissionaudit',
            name='course_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='xapilearnerdatatransmissionaudit',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xapilearnerdatatransmissionaudit',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
