# Generated by Django 3.2.20 on 2023-11-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0032_alter_historicalcanvasenterprisecustomerconfiguration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasenterprisecustomerconfiguration',
            name='enable_incomplete_progress_transmission',
            field=models.BooleanField(default=False, help_text='When set to True, the configured customer will receive learner data transmissions, for incomplete courses as well'),
        ),
        migrations.AddField(
            model_name='historicalcanvasenterprisecustomerconfiguration',
            name='enable_incomplete_progress_transmission',
            field=models.BooleanField(default=False, help_text='When set to True, the configured customer will receive learner data transmissions, for incomplete courses as well'),
        ),
    ]
