# Generated by Django 3.2.22 on 2024-01-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0033_auto_20240110_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvaslearnerassessmentdatatransmissionaudit',
            name='transmission_status',
        ),
        migrations.RemoveField(
            model_name='canvaslearnerdatatransmissionaudit',
            name='transmission_status',
        ),
    ]
