# Generated by Django 3.2.19 on 2024-03-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0034_delete_historicalcanvasenterprisecustomerconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvaslearnerassessmentdatatransmissionaudit',
            name='enterprise_course_enrollment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canvaslearnerdatatransmissionaudit',
            name='enterprise_course_enrollment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='canvaslearnerdatatransmissionaudit',
            index=models.Index(fields=['error_message', 'enterprise_course_enrollment_id'], name='canvas_course_error_idx'),
        ),
    ]
