# Generated by Django 4.2.15 on 2024-08-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0037_canvasenterprisecustomerconfiguration_copy_id_and_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvasenterprisecustomerconfiguration',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='canvasenterprisecustomerconfiguration',
            name='client_secret',
        ),
    ]
