# Generated by Django 4.2.21 on 2025-05-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0039_remove_canvasenterprisecustomerconfiguration_client_id_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='canvaslearnerdatatransmissionaudit',
            new_name='canvas_customer_plugin_idx',
            old_fields=('enterprise_customer_uuid', 'plugin_configuration_id'),
        ),
    ]
