# Generated by Django 3.2.20 on 2023-08-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0027_alter_historicalmoodleenterprisecustomerconfiguration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmoodleenterprisecustomerconfiguration',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical moodle enterprise customer configuration'},
        ),
    ]
