# Generated by Django 3.2.23 on 2024-01-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0030_merge_0028_auto_20231116_1826_0029_auto_20231106_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            old_name='password',
            new_name='deprecated_password',
        ),
        migrations.RenameField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            old_name='token',
            new_name='deprecated_token',
        ),
        migrations.RenameField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            old_name='username',
            new_name='deprecated_username',
        ),
        migrations.RenameField(
            model_name='moodleenterprisecustomerconfiguration',
            old_name='password',
            new_name='deprecated_password',
        ),
        migrations.RenameField(
            model_name='moodleenterprisecustomerconfiguration',
            old_name='token',
            new_name='deprecated_token',
        ),
        migrations.RenameField(
            model_name='moodleenterprisecustomerconfiguration',
            old_name='username',
            new_name='deprecated_username',
        ),
        migrations.AlterField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            name='deprecated_password',
            field=models.CharField(blank=True, help_text="The API user's deprecated password used to obtain new tokens.", max_length=255, verbose_name='Webservice Password'),
        ),
        migrations.AlterField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            name='deprecated_token',
            field=models.CharField(blank=True, help_text="The user's deprecated token for the Moodle webservice.", max_length=255, verbose_name='Webservice User Token'),
        ),
        migrations.AlterField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            name='deprecated_username',
            field=models.CharField(blank=True, help_text="The API user's deprecated username used to obtain new tokens.", max_length=255, verbose_name='Webservice Username'),
        ),
        migrations.AlterField(
            model_name='moodleenterprisecustomerconfiguration',
            name='deprecated_password',
            field=models.CharField(blank=True, help_text="The API user's deprecated password used to obtain new tokens.", max_length=255, verbose_name='Webservice Password'),
        ),
        migrations.AlterField(
            model_name='moodleenterprisecustomerconfiguration',
            name='deprecated_token',
            field=models.CharField(blank=True, help_text="The user's deprecated token for the Moodle webservice.", max_length=255, verbose_name='Webservice User Token'),
        ),
        migrations.AlterField(
            model_name='moodleenterprisecustomerconfiguration',
            name='deprecated_username',
            field=models.CharField(blank=True, help_text="The API user's deprecated username used to obtain new tokens.", max_length=255, verbose_name='Webservice Username'),
        ),
    ]
