# Generated by Django 3.2.23 on 2024-01-16 11:58

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0030_merge_0028_auto_20231116_1826_0029_auto_20231106_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            name='decrypted_password',
        ),
        migrations.RemoveField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            name='decrypted_token',
        ),
        migrations.RemoveField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            name='decrypted_username',
        ),
        migrations.RemoveField(
            model_name='moodleenterprisecustomerconfiguration',
            name='decrypted_password',
        ),
        migrations.RemoveField(
            model_name='moodleenterprisecustomerconfiguration',
            name='decrypted_token',
        ),
        migrations.RemoveField(
            model_name='moodleenterprisecustomerconfiguration',
            name='decrypted_username',
        ),
        migrations.AddField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            name='deprecated_password',
            field=models.CharField(blank=True, help_text="The API user's deprecated password used to obtain new tokens.", max_length=255, verbose_name='Webservice Password'),
        ),
        migrations.AddField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            name='deprecated_token',
            field=models.CharField(blank=True, help_text="The user's deprecated token for the Moodle webservice.", max_length=255, verbose_name='Webservice User Token'),
        ),
        migrations.AddField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            name='deprecated_username',
            field=models.CharField(blank=True, help_text="The API user's deprecated username used to obtain new tokens.", max_length=255, verbose_name='Webservice Username'),
        ),
        migrations.AddField(
            model_name='moodleenterprisecustomerconfiguration',
            name='deprecated_password',
            field=models.CharField(blank=True, help_text="The API user's deprecated password used to obtain new tokens.", max_length=255, verbose_name='Webservice Password'),
        ),
        migrations.AddField(
            model_name='moodleenterprisecustomerconfiguration',
            name='deprecated_token',
            field=models.CharField(blank=True, help_text="The user's deprecated token for the Moodle webservice.", max_length=255, verbose_name='Webservice User Token'),
        ),
        migrations.AddField(
            model_name='moodleenterprisecustomerconfiguration',
            name='deprecated_username',
            field=models.CharField(blank=True, help_text="The API user's deprecated username used to obtain new tokens.", max_length=255, verbose_name='Webservice Username'),
        ),
        migrations.AlterField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            name='password',
            field=fernet_fields.fields.EncryptedCharField(blank=True, help_text="The encrypted API user's password used to obtain new tokens. It will be encrypted when stored in the database.", max_length=255, null=True, verbose_name='Encrypted Webservice Password'),
        ),
        migrations.AlterField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            name='token',
            field=fernet_fields.fields.EncryptedCharField(blank=True, help_text="The encrypted API user's token used to obtain new tokens. It will be encrypted when stored in the database.", max_length=255, null=True, verbose_name='Encrypted Webservice Token'),
        ),
        migrations.AlterField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            name='username',
            field=fernet_fields.fields.EncryptedCharField(blank=True, help_text="The encrypted API user's username used to obtain new tokens. It will be encrypted when stored in the database.", max_length=255, null=True, verbose_name='Encrypted Webservice Username'),
        ),
        migrations.AlterField(
            model_name='moodleenterprisecustomerconfiguration',
            name='password',
            field=fernet_fields.fields.EncryptedCharField(blank=True, help_text="The encrypted API user's password used to obtain new tokens. It will be encrypted when stored in the database.", max_length=255, null=True, verbose_name='Encrypted Webservice Password'),
        ),
        migrations.AlterField(
            model_name='moodleenterprisecustomerconfiguration',
            name='token',
            field=fernet_fields.fields.EncryptedCharField(blank=True, help_text="The encrypted API user's token used to obtain new tokens. It will be encrypted when stored in the database.", max_length=255, null=True, verbose_name='Encrypted Webservice Token'),
        ),
        migrations.AlterField(
            model_name='moodleenterprisecustomerconfiguration',
            name='username',
            field=fernet_fields.fields.EncryptedCharField(blank=True, help_text="The encrypted API user's username used to obtain new tokens. It will be encrypted when stored in the database.", max_length=255, null=True, verbose_name='Encrypted Webservice Username'),
        ),
    ]
