# Generated by Django 3.2.23 on 2023-12-08 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0031_auto_20231204_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            name='token',
        ),
        migrations.RemoveField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            name='use_encrypted_user_data',
        ),
        migrations.RemoveField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            name='username',
        ),
        migrations.RemoveField(
            model_name='moodleenterprisecustomerconfiguration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='moodleenterprisecustomerconfiguration',
            name='token',
        ),
        migrations.RemoveField(
            model_name='moodleenterprisecustomerconfiguration',
            name='use_encrypted_user_data',
        ),
        migrations.RemoveField(
            model_name='moodleenterprisecustomerconfiguration',
            name='username',
        ),
    ]
