# Generated by Django 3.2.22 on 2024-01-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0032_auto_20240117_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodlelearnerdatatransmissionaudit',
            name='transmission_status',
        ),
    ]
