# Generated by Django 3.2.23 on 2024-01-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0032_auto_20240117_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            old_name='decrypted_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            old_name='decrypted_token',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            old_name='decrypted_username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='moodleenterprisecustomerconfiguration',
            old_name='decrypted_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='moodleenterprisecustomerconfiguration',
            old_name='decrypted_token',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='moodleenterprisecustomerconfiguration',
            old_name='decrypted_username',
            new_name='username',
        ),
    ]
