# Generated by Django 3.2.19 on 2024-03-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0033_delete_historicalmoodleenterprisecustomerconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodlelearnerdatatransmissionaudit',
            name='enterprise_course_enrollment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='moodlelearnerdatatransmissionaudit',
            index=models.Index(fields=['error_message', 'enterprise_course_enrollment_id'], name='moodle_course_error_idx'),
        ),
    ]
