# Generated by Django 3.2.11 on 2022-01-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0004_auto_20190830_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xapilearnerdatatransmissionaudit',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='xapilearnerdatatransmissionaudit',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
