# Generated by Django 4.2.21 on 2025-05-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xapi', '0012_xapilearnerdatatransmissionaudit_is_transmitted'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='xapilearnerdatatransmissionaudit',
            new_name='xapi_customer_plugin_idx',
            old_fields=('enterprise_customer_uuid', 'plugin_configuration_id'),
        ),
    ]
