# Generated by Django 2.2.12 on 2020-04-21 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# integrated_channels.sap_success_factors.migrations.0006_sapsuccessfactors_use_enterprise_enrollment_page_waffle_flag
# integrated_channels.sap_success_factors.migrations.0009_sapsuccessfactors_remove_enterprise_enrollment_page_waffle_flag
# integrated_channels.sap_success_factors.migrations.0014_drop_historical_table

class Migration(migrations.Migration):

    replaces = [('sap_success_factors', '0001_initial'), ('sap_success_factors', '0002_auto_20170224_1545'), ('sap_success_factors', '0003_auto_20170317_1402'), ('sap_success_factors', '0004_catalogtransmissionaudit_audit_summary'), ('sap_success_factors', '0005_historicalsapsuccessfactorsenterprisecustomerconfiguration_history_change_reason'), ('sap_success_factors', '0006_sapsuccessfactors_use_enterprise_enrollment_page_waffle_flag'), ('sap_success_factors', '0007_remove_historicalsapsuccessfactorsenterprisecustomerconfiguration_history_change_reason'), ('sap_success_factors', '0008_historicalsapsuccessfactorsenterprisecustomerconfiguration_history_change_reason'), ('sap_success_factors', '0009_sapsuccessfactors_remove_enterprise_enrollment_page_waffle_flag'), ('sap_success_factors', '0010_move_audit_tables_to_base_integrated_channel'), ('sap_success_factors', '0011_auto_20180104_0103'), ('sap_success_factors', '0012_auto_20180109_0712'), ('sap_success_factors', '0013_auto_20180306_1251'), ('sap_success_factors', '0014_drop_historical_table'), ('sap_success_factors', '0015_auto_20180510_1259'), ('sap_success_factors', '0016_sapsuccessfactorsenterprisecustomerconfiguration_additional_locales'), ('sap_success_factors', '0017_sapsuccessfactorsglobalconfiguration_search_student_api_path'), ('sap_success_factors', '0018_sapsuccessfactorsenterprisecustomerconfiguration_show_course_price'), ('sap_success_factors', '0019_auto_20190925_0730'), ('sap_success_factors', '0020_sapsuccessfactorsenterprisecustomerconfiguration_catalogs_to_transmit'), ('sap_success_factors', '0021_sapsuccessfactorsenterprisecustomerconfiguration_show_total_hours'), ('sap_success_factors', '0022_auto_20200206_1046')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waffle', '0001_initial'),
        ('enterprise', '0015_auto_20170130_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerDataTransmissionAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_course_enrollment_id', models.PositiveIntegerField()),
                ('sapsf_user_id', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=255)),
                ('course_completed', models.BooleanField(default=True)),
                ('completed_timestamp', models.BigIntegerField()),
                ('instructor_name', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SAPSuccessFactorsGlobalConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('completion_status_api_path', models.CharField(max_length=255)),
                ('course_api_path', models.CharField(max_length=255)),
                ('oauth_api_path', models.CharField(max_length=255)),
                ('provider_id', models.CharField(default='EDX', max_length=100)),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
        ),
        migrations.CreateModel(
            name='SAPSuccessFactorsEnterpriseCustomerConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('active', models.BooleanField()),
                ('sapsf_base_url', models.CharField(max_length=255, verbose_name='SAP Base URL')),
                ('key', models.CharField(blank=True, max_length=255, verbose_name='Client ID')),
                ('secret', models.CharField(blank=True, max_length=255, verbose_name='Client Secret')),
                ('enterprise_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enterprise.EnterpriseCustomer')),
                ('sapsf_company_id', models.CharField(blank=True, max_length=255, verbose_name='SAP Company ID')),
                ('sapsf_user_id', models.CharField(blank=True, max_length=255, verbose_name='SAP User ID')),
                ('user_type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20, verbose_name='SAP User Type')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogTransmissionAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_customer_uuid', models.UUIDField()),
                ('total_courses', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('audit_summary', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSAPSuccessFactorsEnterpriseCustomerConfiguration',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('active', models.BooleanField()),
                ('sapsf_base_url', models.CharField(max_length=255, verbose_name='SAP Base URL')),
                ('key', models.CharField(blank=True, max_length=255, verbose_name='Client ID')),
                ('secret', models.CharField(blank=True, max_length=255, verbose_name='Client Secret')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('enterprise_customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enterprise.EnterpriseCustomer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sapsf_company_id', models.CharField(blank=True, max_length=255, verbose_name='SAP Company ID')),
                ('sapsf_user_id', models.CharField(blank=True, max_length=255, verbose_name='SAP User ID')),
                ('user_type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20, verbose_name='SAP User Type')),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical sap success factors enterprise customer configuration',
                'get_latest_by': 'history_date',
            },
        ),
        migrations.RunPython(
            code=integrated_channels.sap_success_factors.migrations.0006_sapsuccessfactors_use_enterprise_enrollment_page_waffle_flag.create_switch,
            reverse_code=integrated_channels.sap_success_factors.migrations.0006_sapsuccessfactors_use_enterprise_enrollment_page_waffle_flag.delete_switch,
        ),
        migrations.RemoveField(
            model_name='historicalsapsuccessfactorsenterprisecustomerconfiguration',
            name='history_change_reason',
        ),
        migrations.AddField(
            model_name='historicalsapsuccessfactorsenterprisecustomerconfiguration',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(
            code=integrated_channels.sap_success_factors.migrations.0009_sapsuccessfactors_remove_enterprise_enrollment_page_waffle_flag.delete_switch,
            reverse_code=integrated_channels.sap_success_factors.migrations.0009_sapsuccessfactors_remove_enterprise_enrollment_page_waffle_flag.create_switch,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name='CatalogTransmissionAudit',
                    table='integrated_channel_catalogtransmissionaudit',
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='CatalogTransmissionAudit',
                ),
            ],
        ),
        migrations.RenameModel(
            old_name='LearnerDataTransmissionAudit',
            new_name='SapSuccessFactorsLearnerDataTransmissionAudit',
        ),
        migrations.AlterField(
            model_name='historicalsapsuccessfactorsenterprisecustomerconfiguration',
            name='active',
            field=models.BooleanField(help_text='Is this configuration active ?'),
        ),
        migrations.AlterField(
            model_name='historicalsapsuccessfactorsenterprisecustomerconfiguration',
            name='key',
            field=models.CharField(help_text='OAuth client identifier.', max_length=255, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='historicalsapsuccessfactorsenterprisecustomerconfiguration',
            name='sapsf_base_url',
            field=models.CharField(help_text='Base URL of success factors API.', max_length=255, verbose_name='SAP Base URL'),
        ),
        migrations.AlterField(
            model_name='historicalsapsuccessfactorsenterprisecustomerconfiguration',
            name='sapsf_company_id',
            field=models.CharField(help_text='Success factors company identifier.', max_length=255, verbose_name='SAP Company ID'),
        ),
        migrations.AlterField(
            model_name='historicalsapsuccessfactorsenterprisecustomerconfiguration',
            name='sapsf_user_id',
            field=models.CharField(help_text='Success factors user identifier.', max_length=255, verbose_name='SAP User ID'),
        ),
        migrations.AlterField(
            model_name='historicalsapsuccessfactorsenterprisecustomerconfiguration',
            name='secret',
            field=models.CharField(help_text='OAuth client secret.', max_length=255, verbose_name='Client Secret'),
        ),
        migrations.AlterField(
            model_name='historicalsapsuccessfactorsenterprisecustomerconfiguration',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', help_text='Type of SAP User (admin or user).', max_length=20, verbose_name='SAP User Type'),
        ),
        migrations.AlterField(
            model_name='sapsuccessfactorsenterprisecustomerconfiguration',
            name='active',
            field=models.BooleanField(help_text='Is this configuration active ?'),
        ),
        migrations.AlterField(
            model_name='sapsuccessfactorsenterprisecustomerconfiguration',
            name='enterprise_customer',
            field=models.OneToOneField(help_text='Enterprise Customer associated with the configuration.', on_delete=django.db.models.deletion.CASCADE, to='enterprise.EnterpriseCustomer'),
        ),
        migrations.AlterField(
            model_name='sapsuccessfactorsenterprisecustomerconfiguration',
            name='key',
            field=models.CharField(help_text='OAuth client identifier.', max_length=255, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='sapsuccessfactorsenterprisecustomerconfiguration',
            name='sapsf_base_url',
            field=models.CharField(help_text='Base URL of success factors API.', max_length=255, verbose_name='SAP Base URL'),
        ),
        migrations.AlterField(
            model_name='sapsuccessfactorsenterprisecustomerconfiguration',
            name='sapsf_company_id',
            field=models.CharField(help_text='Success factors company identifier.', max_length=255, verbose_name='SAP Company ID'),
        ),
        migrations.AlterField(
            model_name='sapsuccessfactorsenterprisecustomerconfiguration',
            name='sapsf_user_id',
            field=models.CharField(help_text='Success factors user identifier.', max_length=255, verbose_name='SAP User ID'),
        ),
        migrations.AlterField(
            model_name='sapsuccessfactorsenterprisecustomerconfiguration',
            name='secret',
            field=models.CharField(help_text='OAuth client secret.', max_length=255, verbose_name='Client Secret'),
        ),
        migrations.AlterField(
            model_name='sapsuccessfactorsenterprisecustomerconfiguration',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', help_text='Type of SAP User (admin or user).', max_length=20, verbose_name='SAP User Type'),
        ),
        migrations.AlterField(
            model_name='historicalsapsuccessfactorsenterprisecustomerconfiguration',
            name='active',
            field=models.BooleanField(help_text='Is this configuration active?'),
        ),
        migrations.AlterField(
            model_name='sapsuccessfactorsenterprisecustomerconfiguration',
            name='active',
            field=models.BooleanField(help_text='Is this configuration active?'),
        ),
        migrations.AddField(
            model_name='historicalsapsuccessfactorsenterprisecustomerconfiguration',
            name='transmission_chunk_size',
            field=models.IntegerField(default=500, help_text='The maximum number of data items to transmit to the integrated channel with each request.'),
        ),
        migrations.AddField(
            model_name='sapsuccessfactorsenterprisecustomerconfiguration',
            name='transmission_chunk_size',
            field=models.IntegerField(default=500, help_text='The maximum number of data items to transmit to the integrated channel with each request.'),
        ),
        migrations.RunPython(
            code=integrated_channels.sap_success_factors.migrations.0014_drop_historical_table.dropHistoricalTable,
        ),
        migrations.DeleteModel(
            name='HistoricalSAPSuccessFactorsEnterpriseCustomerConfiguration',
        ),
        migrations.AddField(
            model_name='sapsuccessfactorsenterprisecustomerconfiguration',
            name='additional_locales',
            field=models.TextField(blank=True, default='', help_text='A comma-separated list of additional locales.', verbose_name='Additional Locales'),
        ),
        migrations.AddField(
            model_name='sapsuccessfactorsglobalconfiguration',
            name='search_student_api_path',
            field=models.CharField(default='learning/odatav4/searchStudent/v1/Students', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sapsuccessfactorsenterprisecustomerconfiguration',
            name='show_course_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sapsuccessfactorsenterprisecustomerconfiguration',
            name='channel_worker_username',
            field=models.CharField(blank=True, help_text='Enterprise channel worker username to get JWT tokens for authenticating LMS APIs.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sapsuccessfactorslearnerdatatransmissionaudit',
            name='enterprise_course_enrollment_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AddField(
            model_name='sapsuccessfactorsenterprisecustomerconfiguration',
            name='catalogs_to_transmit',
            field=models.TextField(blank=True, help_text='A comma-separated list of catalog UUIDs to transmit.', null=True),
        ),
        migrations.AddField(
            model_name='sapsuccessfactorsenterprisecustomerconfiguration',
            name='transmit_total_hours',
            field=models.BooleanField(default=False, help_text='Include totalHours in the transmitted completion data', verbose_name='Transmit Total Hours'),
        ),
        migrations.AddField(
            model_name='sapsuccessfactorslearnerdatatransmissionaudit',
            name='total_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
