# Generated by Django 3.2.15 on 2022-10-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_success_factors', '0009_sapsuccessfactorsenterprisecustomerconfiguration_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sapsuccessfactorslearnerdatatransmissionaudit',
            old_name='completed_timestamp',
            new_name='sap_completed_timestamp',
        ),
        migrations.AddField(
            model_name='sapsuccessfactorslearnerdatatransmissionaudit',
            name='completed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
