# Generated by Django 3.2.15 on 2023-01-03 14:55

from django.db import connection, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_success_factors', '0010_move_and_recrete_completed_timestamp'),
    ]

    db_engine = connection.settings_dict['ENGINE']
    if 'sqlite3' in db_engine:
        operations = [
            migrations.AlterIndexTogether(
                name='sapsuccessfactorslearnerdatatransmissionaudit',
                index_together={('enterprise_customer_uuid', 'plugin_configuration_id')},
            ),
        ]
    else:
        operations = [
            migrations.SeparateDatabaseAndState(
                state_operations=[
                    migrations.AlterIndexTogether(
                        name='sapsuccessfactorslearnerdatatransmissionaudit',
                        index_together={('enterprise_customer_uuid', 'plugin_configuration_id')},
                    ),
                ],
                database_operations=[
                    migrations.RunSQL(sql="""
                        CREATE INDEX sapsf_sldta_85936b55_idx
                        ON sap_success_factors_sapsuccessfactorslearnerdatatransmission3ce5 (enterprise_customer_uuid, plugin_configuration_id)
                        ALGORITHM=INPLACE LOCK=NONE
                    """, reverse_sql="""
                        DROP INDEX sapsf_sldta_85936b55_idx
                        ON sap_success_factors_sapsuccessfactorslearnerdatatransmission3ce5
                    """),
                ]
            ),
        ]
