# Generated by Django 3.2.19 on 2023-07-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_success_factors', '0013_sapsuccessfactorsenterprisecustomerconfiguration_last_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapsuccessfactorsenterprisecustomerconfiguration',
            name='show_course_price',
            field=models.BooleanField(default=False, help_text='Displays course price'),
        ),
    ]
