# Generated by Django 3.2.22 on 2024-02-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_success_factors', '0014_alter_sapsuccessfactorsenterprisecustomerconfiguration_show_course_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sapsuccessfactorslearnerdatatransmissionaudit',
            constraint=models.UniqueConstraint(fields=('enterprise_course_enrollment_id', 'course_id'), name='sap_unique_enrollment_course_id'),
        ),
    ]
