# Generated by Django 3.2.19 on 2024-03-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_success_factors', '0015_sapsuccessfactorslearnerdatatransmissionaudit_sap_unique_enrollment_course_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sapsuccessfactorslearnerdatatransmissionaudit',
            index=models.Index(fields=['error_message', 'enterprise_course_enrollment_id'], name='sap_course_error_idx'),
        ),
    ]
