# Generated by Django 3.2.22 on 2024-01-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degreed2', '0024_degreed2learnerdatatransmissionaudit_transmission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degreed2learnerdatatransmissionaudit',
            name='transmission_status',
        ),
    ]
