# Generated by Django 3.2.19 on 2024-03-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degreed2', '0025_delete_historicaldegreed2enterprisecustomerconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreed2learnerdatatransmissionaudit',
            name='enterprise_course_enrollment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='degreed2learnerdatatransmissionaudit',
            index=models.Index(fields=['error_message', 'enterprise_course_enrollment_id'], name='degreed2_course_error_idx'),
        ),
    ]
