# Generated by Django 3.2.11 on 2022-01-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0004_datasharingconsenttextoverrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasharingconsenttextoverrides',
            name='agreement_text',
            field=models.TextField(blank=True, default='', help_text='Text next to agreement check mark'),
        ),
        migrations.AlterField(
            model_name='datasharingconsenttextoverrides',
            name='left_sidebar_text',
            field=models.TextField(blank=True, default='', help_text='Fill in a text for left sidebar paragraph. The following variables may be available:<br /><ul><li>enterprise_customer_name: A name of enterprise customer.</li><li>platform_name: Name of platform.</li><li>item: A string which is "course" or "program" depending on the type of consent.</li><li>course_title: Title of course. Available when type of consent is course.</li><li>course_start_date: Course start date. Available when type of consent is course.</li></ul>'),
        ),
        migrations.AlterField(
            model_name='datasharingconsenttextoverrides',
            name='policy_dropdown_header',
            field=models.CharField(blank=True, default='', help_text='Text of policy drop down', max_length=255),
        ),
        migrations.AlterField(
            model_name='datasharingconsenttextoverrides',
            name='policy_paragraph',
            field=models.TextField(blank=True, default='', help_text='Fill in a text for policy paragraph at the bottom of page. The following variables may be available:<br /><ul><li>enterprise_customer_name: A name of enterprise customer.</li><li>platform_name: Name of platform.</li><li>item: A string which is "course" or "program" depending on the type of consent.</li><li>course_title: Title of course. Available when type of consent is course.</li><li>course_start_date: Course start date. Available when type of consent is course.</li></ul>'),
        ),
        migrations.AlterField(
            model_name='datasharingconsenttextoverrides',
            name='top_paragraph',
            field=models.TextField(blank=True, default='', help_text='Fill in a text for first paragraph of page. The following variables may be available:<br /><ul><li>enterprise_customer_name: A name of enterprise customer.</li><li>platform_name: Name of platform.</li><li>item: A string which is "course" or "program" depending on the type of consent.</li><li>course_title: Title of course. Available when type of consent is course.</li><li>course_start_date: Course start date. Available when type of consent is course.</li></ul>'),
        ),
    ]
