# Generated by Django 3.2.20 on 2023-08-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0006_alter_historicaldatasharingconsent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldatasharingconsent',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Data Sharing Consent Record'},
        ),
    ]
