# Generated by Django 3.2.15 on 2022-09-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrated_channel', '0015_auto_20220718_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmetadataitemtransmission',
            name='content_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
