# Generated by Django 3.2.19 on 2023-07-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrated_channel', '0028_alter_contentmetadataitemtransmission_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericenterprisecustomerpluginconfiguration',
            name='show_course_price',
            field=models.BooleanField(default=False, help_text='Displays course price'),
        ),
    ]
