# Generated by Django 4.2.13 on 2024-05-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrated_channel', '0034_contentmetadataitemtransmission_remote_errored_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericlearnerdatatransmissionaudit',
            name='is_transmitted',
            field=models.BooleanField(default=False),
        ),
    ]
