# Generated by Django 2.2.16 on 2020-10-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0002_moodlelearnerdatatransmissionaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmoodleenterprisecustomerconfiguration',
            name='transmission_chunk_size',
            field=models.IntegerField(default=4, help_text='The maximum number of data items to transmit to the integrated channel with each request.'),
        ),
        migrations.AlterField(
            model_name='moodleenterprisecustomerconfiguration',
            name='transmission_chunk_size',
            field=models.IntegerField(default=4, help_text='The maximum number of data items to transmit to the integrated channel with each request.'),
        ),
    ]
