# Generated by Django 3.2.22 on 2024-02-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0031_auto_20240117_1202'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='moodlelearnerdatatransmissionaudit',
            constraint=models.UniqueConstraint(fields=('enterprise_course_enrollment_id', 'course_id'), name='moodle_unique_enrollment_course_id'),
        ),
    ]
