# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-27 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cornerstone', '0005_auto_20190925_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='cornerstoneenterprisecustomerconfiguration',
            name='real_time_learner_transmission',
            field=models.BooleanField(default=False, help_text='Real time learner transmission enabled for enterprise?'),
        ),
        migrations.AddField(
            model_name='historicalcornerstoneenterprisecustomerconfiguration',
            name='real_time_learner_transmission',
            field=models.BooleanField(default=False, help_text='Real time learner transmission enabled for enterprise?'),
        ),
    ]
