# Generated by Django 3.2.20 on 2023-08-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cornerstone', '0029_alter_historicalcornerstoneenterprisecustomerconfiguration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcornerstoneenterprisecustomerconfiguration',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical cornerstone enterprise customer configuration'},
        ),
    ]
