# Generated by Django 3.2.20 on 2023-11-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cornerstone', '0030_auto_20231010_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='cornerstoneenterprisecustomerconfiguration',
            name='enable_incomplete_progress_transmission',
            field=models.BooleanField(default=True, help_text='When set to True, the configured customer will receive learner data transmissions, for incomplete courses as well'),
        ),
        migrations.AddField(
            model_name='historicalcornerstoneenterprisecustomerconfiguration',
            name='enable_incomplete_progress_transmission',
            field=models.BooleanField(default=True, help_text='When set to True, the configured customer will receive learner data transmissions, for incomplete courses as well'),
        ),
    ]
