# Generated by Django 3.2.23 on 2024-01-23 10:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0198_alter_enterprisecourseenrollment_options'),
        ('cornerstone', '0030_auto_20231010_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='CornerstoneAPIRequestLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('enterprise_customer_configuration_id', models.IntegerField(help_text='ID from the EnterpriseCustomerConfiguration model')),
                ('endpoint', models.TextField()),
                ('payload', models.TextField()),
                ('time_taken', models.FloatField()),
                ('status_code', models.PositiveIntegerField(blank=True, help_text='API call response HTTP status code', null=True)),
                ('response_body', models.TextField(blank=True, help_text='API call response body', null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('enterprise_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.enterprisecustomer')),
            ],
            options={
                'verbose_name_plural': 'Cornerstone API request logs',
            },
        ),
    ]
