# Generated by Django 3.2.23 on 2024-01-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cornerstone', '0032_cornerstonelearnerdatatransmissionaudit_transmission_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cornerstoneapirequestlogs',
            options={'verbose_name_plural': 'Cornerstone API request logs'},
        ),
    ]
