# Generated by Django 3.2.19 on 2024-03-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cornerstone', '0033_delete_historicalcornerstoneenterprisecustomerconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cornerstonelearnerdatatransmissionaudit',
            name='enterprise_course_enrollment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='cornerstonelearnerdatatransmissionaudit',
            index=models.Index(fields=['error_message', 'enterprise_course_enrollment_id'], name='cornerstone_course_error_idx'),
        ),
    ]
