# Generated by Django 4.2.21 on 2025-05-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cornerstone', '0034_cornerstonelearnerdatatransmissionaudit_is_transmitted'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cornerstonelearnerdatatransmissionaudit',
            new_name='corner_customer_plugin_idx',
            old_fields=('enterprise_customer_uuid', 'plugin_configuration_id'),
        ),
    ]
