name: Publish edx/edx-enterprise to PyPI

on:
  release:
    types: [published]
    branches: [master]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Nodejs Env
        run: echo "NODE_VER=`cat .nvmrc`" >> $GITHUB_ENV
      - name: setup python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.12
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ env.NODE_VER }}
      - name: Install gettext
        run: sudo apt-get update && sudo apt-get install -y gettext
      - name: Install requirements
        run: make requirements
      - name: Pull translations
        run: make pull_translations
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_UPLOAD_TOKEN }}
