# Generated by Django 2.2.17 on 2021-01-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_auto_20210111_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisefeatureuserroleassignment',
            name='applies_to_all_contexts',
            field=models.BooleanField(default=False, help_text='If true, indicates that the user is effectively assigned their role for any and all contexts. Defaults to False.'),
        ),
        migrations.AddField(
            model_name='systemwideenterpriseuserroleassignment',
            name='applies_to_all_contexts',
            field=models.BooleanField(default=False, help_text='If true, indicates that the user is effectively assigned their role for any and all contexts. Defaults to False.'),
        ),
    ]
