# Generated by Django 2.2.19 on 2021-11-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0146_enterprise_customer_invite_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomer',
            name='enable_universal_link',
            field=models.BooleanField(default=False, help_text='Specifies whether to allow univeral link generation in the admin portal.'),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomer',
            name='enable_universal_link',
            field=models.BooleanField(default=False, help_text='Specifies whether to allow univeral link generation in the admin portal.'),
        ),
    ]
