# Generated by Django 2.2.19 on 2022-05-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0156_add_is_active_role_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsystemwideenterpriseuserroleassignment',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemwideenterpriseuserroleassignment',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
