# Generated by Django 3.2.19 on 2023-05-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0172_auto_20230517_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecourseenrollment',
            name='unenrolled_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, help_text="Specifies when an enterprise course enrollment's course enrollment object was unenrolled.", null=True),
        ),
        migrations.AddField(
            model_name='historicalenterprisecourseenrollment',
            name='unenrolled_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, help_text="Specifies when an enterprise course enrollment's course enrollment object was unenrolled.", null=True),
        ),
    ]
