# Generated by Django 3.2.21 on 2023-10-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0189_auto_20231002_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomer',
            name='enable_programs',
            field=models.BooleanField(default=True, help_text='If checked, the learners will be able to see the programs on the learner portal dashboard.', verbose_name='Display programs screen'),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomer',
            name='enable_programs',
            field=models.BooleanField(default=True, help_text='If checked, the learners will be able to see the programs on the learner portal dashboard.', verbose_name='Display programs screen'),
        ),
    ]
