# Generated by Django 5.2.8 on 2026-04-10

from django.db import migrations


def enable_academies_for_search_enabled_customers(apps, schema_editor):
    """
    Enable academies for all existing enterprise customers that have
    integrated learner portal search enabled.
    """
    EnterpriseCustomer = apps.get_model('enterprise', 'EnterpriseCustomer')
    EnterpriseCustomer.objects.filter(
        enable_integrated_customer_learner_portal_search=True,
    ).update(enable_academies=True)


def reverse_migration(apps, schema_editor):
    """
    Reverse is a no-op since we cannot determine which customers
    previously had enable_academies=False.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0243_add_reminder_sent_at_to_pending_admin"),
    ]

    operations = [
        migrations.RunPython(
            enable_academies_for_search_enabled_customers,
            reverse_migration,
        ),
    ]
