# Generated by Django 5.2.15 on 2026-06-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0246_enrollment_email_update_02"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprisecustomer",
            name="enable_credit_and_industry_pathways",
            field=models.BooleanField(
                default=False,
                help_text="Controls the visibility of Credit and Industry Pathways in the learner portal.",
                verbose_name="Display credit and industry pathways",
            ),
        ),
        migrations.AddField(
            model_name="historicalenterprisecustomer",
            name="enable_credit_and_industry_pathways",
            field=models.BooleanField(
                default=False,
                help_text="Controls the visibility of Credit and Industry Pathways in the learner portal.",
                verbose_name="Display credit and industry pathways",
            ),
        ),
    ]
