# Generated by Django 5.2.13 on 2026-07-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "enterprise",
            "0248_alter_enterprisecustomer_enable_credit_and_industry_pathways_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprisecustomer",
            name="enable_people_management",
            field=models.BooleanField(
                default=True,
                help_text="Automatically enabled. Displays organization learners and invite admins.",
                verbose_name="Display people management",
            ),
        ),
        migrations.AddField(
            model_name="historicalenterprisecustomer",
            name="enable_people_management",
            field=models.BooleanField(
                default=True,
                help_text="Automatically enabled. Displays organization learners and invite admins.",
                verbose_name="Display people management",
            ),
        ),
    ]
