# Generated by Django 4.2.28 on 2026-08-04 11:06

import django.db.models.deletion
from django.db import migrations, models

import enterprise.models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0249_enterprisecustomer_enable_people_management_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisecustomer',
            name='customer_type',
            field=models.ForeignKey(default=enterprise.models.get_default_customer_type, help_text='Selecting the "Non-production" customer type displays a banner in the administrator and learner portals indicating that this is not a production portal.', on_delete=django.db.models.deletion.CASCADE, to='enterprise.enterprisecustomertype', verbose_name='Customer Type'),
        ),
        migrations.AlterField(
            model_name='historicalenterprisecustomer',
            name='customer_type',
            field=models.ForeignKey(blank=True, db_constraint=False, default=enterprise.models.get_default_customer_type, help_text='Selecting the "Non-production" customer type displays a banner in the administrator and learner portals indicating that this is not a production portal.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enterprise.enterprisecustomertype', verbose_name='Customer Type'),
        ),
    ]
