# Generated by Django 4.2.30 on 2026-08-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0251_add_non_production_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisecustomer',
            name='enable_demo_data_for_analytics_and_lpr',
            field=models.BooleanField(default=False, help_text='Display demo data from analytics and the learner progress report for demo customers. Dummy data will only appear if the enterprise user is also registered as an admin on the analytics demo portal. Contact the support team or use Django admin to set this up.', verbose_name='Enable demo data from analytics and lpr'),
        ),
        migrations.AlterField(
            model_name='historicalenterprisecustomer',
            name='enable_demo_data_for_analytics_and_lpr',
            field=models.BooleanField(default=False, help_text='Display demo data from analytics and the learner progress report for demo customers. Dummy data will only appear if the enterprise user is also registered as an admin on the analytics demo portal. Contact the support team or use Django admin to set this up.', verbose_name='Enable demo data from analytics and lpr'),
        ),
    ]
